function normalizar(texto) {
  return texto
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .toUpperCase()
    .replace(/[^A-Z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '');
}

function crearGeneradorCodigo() {
  const usados = new Set();
  return function generarCodigo(nombre) {
    const base = normalizar(nombre).slice(0, 46);
    let codigo = base;
    let sufijo = 2;
    while (usados.has(codigo)) {
      codigo = `${base.slice(0, 46 - String(sufijo).length - 1)}_${sufijo}`;
      sufijo += 1;
    }
    usados.add(codigo);
    return codigo;
  };
}

const estudiosPorCategoria = {
  Hematología: [
    ['Biometría hemática completa / Hemograma / CBC'],
    ['Hematocrito / PCV'],
    ['Hemoglobina'],
    ['Conteo de eritrocitos'],
    ['Conteo de leucocitos'],
    ['Conteo de plaquetas'],
    ['Volumen corpuscular medio — VCM'],
    ['Hemoglobina corpuscular media — HCM'],
    ['Concentración media de hemoglobina corpuscular — CHCM'],
    ['Ancho de distribución eritrocitaria — RDW'],
    ['Volumen plaquetario medio — VPM/MPV'],
    ['Proteínas plasmáticas totales'],
    ['Fibrinógeno'],
    ['Diferencial leucocitario'],
    ['Frotis sanguíneo'],
    ['Frotis sanguíneo felino', null, 'Gato'],
    ['Recuento de reticulocitos'],
    ['Evaluación morfológica eritrocitaria'],
    ['Evaluación morfológica leucocitaria'],
    ['Evaluación morfológica plaquetaria'],
    ['Conteo manual de plaquetas'],
    ['Búsqueda de hemoparásitos'],
    ['Cuerpos de Heinz'],
    ['Esferocitos'],
    ['Aglutinación eritrocitaria'],
    ['Prueba de autoaglutinación salina'],
    ['Neutrófilos'],
    ['Neutrófilos en banda'],
    ['Linfocitos'],
    ['Monocitos'],
    ['Eosinófilos'],
    ['Basófilos'],
    ['Evaluación de leucocitos anormales'],
    ['Evaluación morfológica de eritrocitos'],
    ['Evaluación morfológica de leucocitos'],
    ['Evaluación morfológica de plaquetas'],
    ['Reticulocitos corregidos'],
    ['Índice de producción reticulocitaria'],
  ],
  'Química sanguínea / Bioquímica': [
    ['Glucosa'],
    ['Fructosamina'],
    ['Hemoglobina glucosilada'],
    ['Lactato'],
    ['Piruvato'],
    ['Beta-hidroxibutirato / cuerpos cetónicos'],
    ['Urea / BUN'],
    ['Creatinina'],
    ['SDMA'],
    ['Relación BUN/creatinina'],
    ['Cistatina C'],
    ['Tasa de filtración glomerular'],
    ['Depuración renal con iohexol'],
    ['ALT / TGP'],
    ['AST / TGO'],
    ['ALKP / Fosfatasa alcalina', null, 'Perro'],
    ['ALKP / Fosfatasa alcalina', null, 'Gato'],
    ['GGT'],
    ['Bilirrubina total'],
    ['Bilirrubina directa'],
    ['Bilirrubina indirecta'],
    ['Ácidos biliares preprandiales'],
    ['Ácidos biliares postprandiales'],
    ['Amonio / amoníaco'],
    ['Colesterol'],
    ['Triglicéridos'],
    ['Proteínas totales'],
    ['Albúmina'],
    ['Globulinas'],
    ['Relación albúmina/globulina'],
    ['Electroforesis de proteínas séricas'],
    ['Amilasa'],
    ['Lipasa'],
    ['Lipasa pancreática específica canina — cPL / Spec cPL', null, 'Perro'],
    ['Lipasa pancreática específica felina — fPL / Spec fPL', null, 'Gato'],
    ['TLI canina', null, 'Perro'],
    ['TLI felina', null, 'Gato'],
    ['Cobalamina / vitamina B12'],
    ['Folato / ácido fólico'],
    ['Gastrina'],
    ['Tripsina'],
    ['Alfa-1 inhibidor de proteasas fecal'],
    ['Elastasa pancreática fecal'],
    ['Creatina quinasa / CK / CPK'],
    ['LDH'],
    ['Aldolasa'],
  ],
  'Electrolitos, minerales y ácido-base': [
    ['Sodio'],
    ['Potasio'],
    ['Cloro'],
    ['Calcio total'],
    ['Calcio ionizado'],
    ['Fósforo'],
    ['Magnesio'],
    ['Hierro sérico'],
    ['Ferritina'],
    ['Capacidad total de fijación de hierro — TIBC'],
    ['Saturación de transferrina'],
    ['Cobre sérico'],
    ['Zinc sérico'],
    ['Selenio'],
    ['Manganeso'],
    ['Gasometría arterial'],
    ['Gasometría venosa'],
    ['pH sanguíneo'],
    ['pCO₂'],
    ['pO₂'],
    ['Bicarbonato'],
    ['Exceso de base'],
    ['Anion gap'],
    ['Osmolalidad sérica'],
  ],
  Uroanálisis: [
    ['Uroanálisis completo', null, 'Perro'],
    ['Uroanálisis completo', null, 'Gato'],
    ['Examen general de orina / EGO'],
    ['Sedimento urinario'],
    ['Relación proteína/creatinina urinaria — UPC'],
    ['Microalbuminuria'],
    ['Glucosuria cuantitativa'],
    ['Electrolitos urinarios'],
    ['Fracción excretada de sodio'],
    ['Fracción excretada de potasio'],
    ['Osmolalidad urinaria'],
    ['Cortisol/creatinina urinaria'],
    ['Cultivo de orina'],
    ['Antibiograma urinario'],
    ['Análisis de cálculos urinarios / urolitos'],
    ['Color'],
    ['Aspecto'],
    ['Densidad urinaria'],
    ['pH'],
    ['Proteínas'],
    ['Glucosa urinaria'],
    ['Cetonas'],
    ['Bilirrubina'],
    ['Sangre / hemoglobina'],
    ['Urobilinógeno'],
    ['Eritrocitos'],
    ['Leucocitos'],
    ['Células epiteliales'],
    ['Cilindros'],
    ['Cristales'],
    ['Bacterias'],
    ['Levaduras'],
    ['Espermatozoides'],
    ['Parásitos urinarios'],
  ],
  'Coagulación y hemostasia': [
    ['Tiempo de protrombina — PT'],
    ['Tiempo parcial de tromboplastina activada — aPTT'],
    ['Tiempo de coagulación activado — ACT'],
    ['Tiempo de sangrado de mucosa bucal — BMBT'],
    ['Fibrinógeno'],
    ['Dímero D'],
    ['Productos de degradación de fibrina'],
    ['Antitrombina III'],
    ['Tromboelastografía — TEG'],
    ['Tromboelastometría — ROTEM'],
    ['Factor de von Willebrand'],
    ['Factor VIII'],
    ['Factor IX'],
    ['Factor VII'],
    ['Proteína C'],
    ['Panel de coagulación'],
    ['Panel de coagulación intravascular diseminada — CID/DIC'],
  ],
  Endocrinología: [
    ['T4 total'],
    ['T4 libre'],
    ['T4 libre por diálisis de equilibrio'],
    ['T3 total'],
    ['T3 libre'],
    ['TSH'],
    ['Anticuerpos antitiroglobulina'],
    ['Anticuerpos anti-T3'],
    ['Anticuerpos anti-T4'],
    ['Panel tiroideo felino', null, 'Gato'],
    ['Panel tiroideo canino', null, 'Perro'],
    ['Cortisol basal'],
    ['Prueba de estimulación con ACTH'],
    ['Supresión con dexametasona a dosis baja'],
    ['Supresión con dexametasona a dosis alta'],
    ['ACTH endógena'],
    ['Aldosterona'],
    ['Renina'],
    ['Relación aldosterona/renina'],
    ['17-hidroxiprogesterona'],
    ['Androstenediona'],
    ['Cortisol/creatinina urinaria'],
    ['Panel de hormonas adrenales'],
    ['PTH'],
    ['PTHrP'],
    ['Progesterona'],
    ['Estradiol'],
    ['Testosterona'],
    ['Hormona antimülleriana — AMH'],
    ['LH'],
    ['FSH'],
    ['Relaxina'],
    ['Inhibina'],
  ],
  'Enfermedades infecciosas - Perro': [
    ['Ehrlichia canis — anticuerpos', null, 'Perro'],
    ['Ehrlichia canis — PCR', null, 'Perro'],
    ['Ehrlichia ewingii — PCR', null, 'Perro'],
    ['Anaplasma phagocytophilum — anticuerpos', null, 'Perro'],
    ['Anaplasma phagocytophilum — PCR', null, 'Perro'],
    ['Anaplasma platys — PCR', null, 'Perro'],
    ['Borrelia burgdorferi / Lyme — anticuerpos', null, 'Perro'],
    ['Borrelia burgdorferi — PCR', null, 'Perro'],
    ['Lyme C6', null, 'Perro'],
    ['Babesia canis — PCR', null, 'Perro'],
    ['Babesia vogeli — PCR', null, 'Perro'],
    ['Babesia gibsoni — PCR', null, 'Perro'],
    ['Hepatozoon canis — PCR', null, 'Perro'],
    ['Hepatozoon americanum — PCR', null, 'Perro'],
    ['Rickettsia rickettsii — serología', null, 'Perro'],
    ['Rickettsia spp. — PCR', null, 'Perro'],
    ['Bartonella spp. — PCR', null, 'Perro'],
    ['Bartonella spp. — serología', null, 'Perro'],
    ['Panel de enfermedades transmitidas por garrapatas', null, 'Perro'],
    ['Moquillo / Distemper — PCR', null, 'Perro'],
    ['Moquillo — anticuerpos', null, 'Perro'],
    ['Parvovirus canino — antígeno fecal', null, 'Perro'],
    ['Parvovirus canino — PCR', null, 'Perro'],
    ['Adenovirus canino tipo 1 — PCR', null, 'Perro'],
    ['Adenovirus canino tipo 2 — PCR', null, 'Perro'],
    ['Parainfluenza canina — PCR', null, 'Perro'],
    ['Coronavirus entérico canino — PCR', null, 'Perro'],
    ['Coronavirus respiratorio canino — PCR', null, 'Perro'],
    ['Herpesvirus canino — PCR', null, 'Perro'],
    ['Influenza canina — PCR', null, 'Perro'],
    ['Influenza A — PCR', null, 'Perro'],
    ['Pneumovirus canino — PCR', null, 'Perro'],
    ['Brucella canis — serología', null, 'Perro'],
    ['Brucella canis — PCR', null, 'Perro'],
    ['Leptospira spp. — PCR', null, 'Perro'],
    ['Leptospira — MAT', null, 'Perro'],
    ['Leishmania — ELISA', null, 'Perro'],
    ['Leishmania — PCR', null, 'Perro'],
    ['Neospora caninum — anticuerpos', null, 'Perro'],
    ['Neospora caninum — PCR', null, 'Perro'],
    ['SNAP 4Dx / panel vectorial', null, 'Perro'],
    ['Panel respiratorio canino PCR', null, 'Perro'],
    ['Panel gastrointestinal canino PCR', null, 'Perro'],
    ['Panel neurológico infeccioso canino', null, 'Perro'],
    ['Panel de donador sanguíneo canino', null, 'Perro'],
  ],
  'Enfermedades infecciosas - Gato': [
    ['FeLV antígeno', null, 'Gato'],
    ['FeLV ELISA', null, 'Gato'],
    ['FeLV IFA', null, 'Gato'],
    ['FeLV PCR', null, 'Gato'],
    ['FIV anticuerpos', null, 'Gato'],
    ['FIV ELISA', null, 'Gato'],
    ['FIV Western Blot', null, 'Gato'],
    ['FIV PCR', null, 'Gato'],
    ['Prueba rápida ViLeF/VIF (FeLV/FIV)', null, 'Gato'],
    ['PCR para ViLeF/VIF (FeLV/FIV)', null, 'Gato'],
    ['Coronavirus felino — FCoV anticuerpos', null, 'Gato'],
    ['Coronavirus felino — PCR', null, 'Gato'],
    ['FCoV PCR cuantitativa', null, 'Gato'],
    ['Coronavirus felino en derrame', null, 'Gato'],
    ['Coronavirus felino en tejido', null, 'Gato'],
    ['FIP/PIF inmunohistoquímica', null, 'Gato'],
    ['FIP/PIF PCR', null, 'Gato'],
    ['FIP mRNA', null, 'Gato'],
    ['Herpesvirus felino tipo 1 — PCR', null, 'Gato'],
    ['Calicivirus felino — PCR', null, 'Gato'],
    ['Chlamydia felis — PCR', null, 'Gato'],
    ['Bordetella bronchiseptica — PCR', null, 'Gato'],
    ['Mycoplasma felis — PCR', null, 'Gato'],
    ['Panel respiratorio felino PCR', null, 'Gato'],
    ['Panleucopenia felina — antígeno', null, 'Gato'],
    ['Panleucopenia felina — PCR', null, 'Gato'],
    ['Bartonella henselae — PCR', null, 'Gato'],
    ['Bartonella — serología', null, 'Gato'],
    ['Hemoplasma / Mycoplasma haemofelis — PCR', null, 'Gato'],
    ['PCR para hemoplasmas', null, 'Gato'],
    ['Candidatus Mycoplasma haemominutum — PCR', null, 'Gato'],
    ['Candidatus Mycoplasma turicensis — PCR', null, 'Gato'],
    ['Cytauxzoon felis — PCR', null, 'Gato'],
    ['Toxoplasma gondii IgG', null, 'Gato'],
    ['Toxoplasma gondii IgM', null, 'Gato'],
    ['Toxoplasma gondii PCR', null, 'Gato'],
    ['Tritrichomonas foetus PCR', null, 'Gato'],
    ['Giardia PCR', null, 'Gato'],
    ['Cryptosporidium PCR', null, 'Gato'],
    ['Panel gastrointestinal felino PCR', null, 'Gato'],
    ['Panel neurológico infeccioso felino', null, 'Gato'],
    ['Panel de donador sanguíneo felino', null, 'Gato'],
  ],
  Parasitología: [
    ['Coprológico por flotación', null, 'Perro'],
    ['Coprológico funcional / digestivo', null, 'Perro'],
    ['Coprológico por flotación', null, 'Gato'],
    ['Coprológico por extensión directa', null, 'Gato'],
    ['Examen coproparasitoscópico'],
    ['Examen coproparasitoscópico directo'],
    ['Flotación fecal'],
    ['Flotación fecal por centrifugación'],
    ['Sedimentación fecal'],
    ['Técnica de Baermann'],
    ['Conteo de huevos fecales'],
    ['Giardia — ELISA'],
    ['Giardia — inmunofluorescencia'],
    ['Giardia — PCR'],
    ['Cryptosporidium — PCR'],
    ['Cryptosporidium — inmunofluorescencia'],
    ['Toxocara spp.'],
    ['Ancylostoma spp.'],
    ['Trichuris vulpis'],
    ['Strongyloides spp.'],
    ['Dipylidium caninum', null, 'Perro'],
    ['Taenia spp.'],
    ['Echinococcus spp.'],
    ['Cystoisospora spp.'],
    ['Tritrichomonas foetus'],
    ['Toxoplasma gondii'],
    ['Neospora caninum', null, 'Perro'],
    ['Dirofilaria immitis — antígeno'],
    ['Dirofilaria immitis — PCR'],
    ['Microfilarias — prueba de Knott'],
    ['Angiostrongylus spp.'],
    ['Aelurostrongylus abstrusus'],
    ['Capillaria / Eucoleus spp.'],
  ],
  Bacteriología: [
    ['Cultivo bacteriano aerobio', 'tipo_muestra'],
    ['Cultivo bacteriano anaerobio', 'tipo_muestra'],
    ['Hemocultivo', 'tipo_muestra'],
    ['Urocultivo', 'tipo_muestra'],
    ['Cultivo de piel', 'tipo_muestra'],
    ['Cultivo de heridas', 'tipo_muestra'],
    ['Cultivo de oído', 'tipo_muestra'],
    ['Cultivo ocular', 'tipo_muestra'],
    ['Cultivo nasal', 'tipo_muestra'],
    ['Cultivo respiratorio', 'tipo_muestra'],
    ['Cultivo de lavado broncoalveolar', 'tipo_muestra'],
    ['Cultivo de líquido sinovial', 'tipo_muestra'],
    ['Cultivo de líquido cefalorraquídeo', 'tipo_muestra'],
    ['Cultivo de líquidos cavitarios', 'tipo_muestra'],
    ['Cultivo de tejidos', 'tipo_muestra'],
    ['Cultivo genital', 'tipo_muestra'],
    ['Cultivo fecal', 'tipo_muestra'],
    ['Antibiograma', 'tipo_muestra'],
    ['Concentración mínima inhibitoria — MIC'],
    ['Tinción de Gram'],
    ['Tinción ácido-alcohol resistente'],
    ['Identificación bacteriana por MALDI-TOF'],
    ['Cultivo de sangre / hemocultivo', 'tipo_muestra'],
    ['Cultivo de orina / urocultivo', 'tipo_muestra'],
  ],
  Micología: [
    ['Examen directo para hongos'],
    ['Citología para hongos'],
    ['Cultivo micológico'],
    ['Dermatofitos — cultivo DTM'],
    ['Dermatofitos — PCR'],
    ['Microsporum canis'],
    ['Microsporum gypseum'],
    ['Trichophyton spp.'],
    ['Malassezia spp.'],
    ['Cryptococcus — antígeno'],
    ['Cryptococcus — cultivo'],
    ['Cryptococcus — PCR'],
    ['Histoplasma — antígeno'],
    ['Histoplasma — PCR'],
    ['Blastomyces — antígeno'],
    ['Blastomyces — PCR'],
    ['Coccidioides — anticuerpos'],
    ['Coccidioides — PCR'],
    ['Aspergillus — serología'],
    ['Aspergillus — PCR'],
    ['Sporothrix — cultivo'],
    ['Sporothrix — PCR'],
    ['Sensibilidad antifúngica'],
  ],
  Dermatología: [
    ['Raspado cutáneo superficial'],
    ['Raspado cutáneo profundo'],
    ['Tricograma'],
    ['Citología cutánea'],
    ['Citología por impresión'],
    ['Citología con cinta adhesiva'],
    ['Citología de pústulas'],
    ['Citología ótica'],
    ['Cultivo bacteriano de piel', 'tipo_muestra'],
    ['Cultivo micológico'],
    ['PCR de dermatofitos'],
    ['Biopsia cutánea'],
    ['Histopatología dermatológica'],
    ['Inmunohistoquímica de piel'],
    ['Inmunofluorescencia directa'],
    ['Prueba intradérmica de alergia'],
    ['IgE específica de alérgenos'],
    ['Panel de alergias ambientales'],
    ['Panel de alérgenos alimentarios'],
  ],
  Citología: [
    ['Citología de piel', 'tejido_lateralidad', 'Perro'],
    ['Punción con aguja fina (PAF)', 'tejido_lateralidad', 'Perro'],
    ['Citología de raspado de oreja', null, 'Gato'],
    ['Punción con aguja fina (PAF) de masas hepáticas', null, 'Gato'],
    ['Punción con aguja fina (PAF) de nódulos tiroideos', null, 'Gato'],
    ['Citología por aspiración con aguja fina — PAAF/FNA', 'tejido_lateralidad'],
    ['Citología de masa', 'tejido_lateralidad'],
    ['Citología de ganglio linfático', 'tejido_lateralidad'],
    ['Citología de médula ósea', 'tejido_lateralidad'],
    ['Citología cutánea', 'tejido_lateralidad'],
    ['Citología ótica', 'tejido_lateralidad'],
    ['Citología vaginal', 'tejido_lateralidad'],
    ['Citología conjuntival', 'tejido_lateralidad'],
    ['Citología nasal', 'tejido_lateralidad'],
    ['Citología de líquido pleural', 'tejido_lateralidad'],
    ['Citología de líquido peritoneal', 'tejido_lateralidad'],
    ['Citología de líquido pericárdico', 'tejido_lateralidad'],
    ['Citología de líquido sinovial', 'tejido_lateralidad'],
    ['Citología de líquido cefalorraquídeo', 'tejido_lateralidad'],
    ['Citología de lavado broncoalveolar', 'tejido_lateralidad'],
    ['Citología de lavado traqueal', 'tejido_lateralidad'],
    ['Citología de próstata', 'tejido_lateralidad'],
    ['Citología de hígado', 'tejido_lateralidad'],
    ['Citología de bazo', 'tejido_lateralidad'],
    ['Citología renal', 'tejido_lateralidad'],
    ['Citología de lesiones óseas', 'tejido_lateralidad'],
    ['Citología de tumores', 'tejido_lateralidad'],
  ],
  'Anatomía patológica': [
    ['Biopsia', 'tejido_lateralidad'],
    ['Histopatología', 'tejido_lateralidad'],
    ['Histopatología de piel', 'tejido_lateralidad'],
    ['Histopatología gastrointestinal', 'tejido_lateralidad'],
    ['Histopatología hepática', 'tejido_lateralidad'],
    ['Histopatología renal', 'tejido_lateralidad'],
    ['Histopatología pulmonar', 'tejido_lateralidad'],
    ['Histopatología de ganglio', 'tejido_lateralidad'],
    ['Histopatología de médula ósea', 'tejido_lateralidad'],
    ['Histopatología de masa/tumor', 'tejido_lateralidad'],
    ['Histopatología ósea', 'tejido_lateralidad'],
    ['Histopatología ocular', 'tejido_lateralidad'],
    ['Histopatología cerebral', 'tejido_lateralidad'],
    ['Histopatología reproductiva', 'tejido_lateralidad'],
    ['Inmunohistoquímica', 'tejido_lateralidad'],
    ['Tinciones especiales', 'tejido_lateralidad'],
    ['Márgenes quirúrgicos tumorales', 'tejido_lateralidad'],
    ['Grado histológico tumoral', 'tejido_lateralidad'],
    ['Necropsia'],
    ['Necropsia completa'],
    ['Necropsia parcial'],
    ['Histopatología post mortem'],
  ],
  'Oncología y diagnóstico molecular': [
    ['Citología de neoplasia'],
    ['Histopatología tumoral'],
    ['Inmunohistoquímica tumoral'],
    ['Citometría de flujo'],
    ['PARR / clonabilidad linfocitaria'],
    ['Panel para linfoma'],
    ['Panel para leucemia'],
    ['Inmunofenotipo de linfoma'],
    ['Aspirado de médula ósea'],
    ['Biopsia de médula ósea'],
    ['BRAF urinario para carcinoma urotelial'],
    ['Mutación BRAF V595E'],
    ['KIT / c-KIT'],
    ['Ki-67'],
    ['Índice mitótico'],
    ['Receptores hormonales tumorales'],
    ['Secuenciación molecular de tumores'],
    ['Panel genómico oncológico'],
    ['Biopsia líquida / ADN tumoral circulante'],
  ],
  Cardiología: [
    ['Cardiopet proBNP felino', null, 'Gato'],
    ['Troponina I cardiaca'],
    ['NT-proBNP'],
    ['BNP'],
    ['Electrocardiograma — ECG'],
    ['ECG de 6 derivaciones'],
    ['Holter 24 horas'],
    ['Holter 48 horas'],
    ['Monitor de eventos cardiacos'],
    ['Ecocardiograma'],
    ['Ecocardiograma Doppler'],
    ['Doppler color'],
    ['Presión arterial sistémica'],
    ['Presión arterial Doppler'],
    ['Presión arterial oscilométrica'],
  ],
  Imagenología: [
    ['Radiografía simple', 'zona'],
    ['Radiografía de contraste', 'zona'],
    ['Esofagograma'],
    ['Tránsito gastrointestinal'],
    ['Colon por contraste'],
    ['Urografía excretora'],
    ['Cistografía'],
    ['Uretrografía'],
    ['Fistulografía'],
    ['Mielografía'],
    ['Ultrasonido', 'zona'],
    ['Ultrasonido gestacional'],
    ['Ultrasonido Doppler', 'zona'],
    ['Ecografía FAST / AFAST'],
    ['Ecografía TFAST'],
    ['POCUS', 'zona'],
    ['Tomografía computarizada — CT/TAC', 'zona'],
    ['TAC con contraste', 'zona'],
    ['Angio-TAC', 'zona'],
    ['Resonancia magnética — MRI/RM', 'zona'],
    ['Resonancia con contraste', 'zona'],
    ['Gammagrafía / medicina nuclear', 'zona'],
    ['PET/CT', 'zona'],
  ],
  Neurología: [
    ['Análisis de líquido cefalorraquídeo'],
    ['Citología de LCR'],
    ['Proteínas de LCR'],
    ['Cultivo de LCR', 'tipo_muestra'],
    ['PCR de agentes infecciosos en LCR'],
    ['Panel neurológico PCR'],
    ['Resonancia magnética cerebral'],
    ['Resonancia de columna'],
    ['Tomografía cerebral'],
    ['Mielografía'],
    ['Electroencefalograma — EEG'],
    ['Electromiografía — EMG'],
    ['Velocidad de conducción nerviosa'],
    ['Potenciales evocados'],
    ['Biopsia de nervio', 'tejido_lateralidad'],
    ['Biopsia muscular', 'tejido_lateralidad'],
    ['Anticuerpos contra receptor de acetilcolina'],
    ['CK'],
    ['Panel de enfermedades neuromusculares'],
    ['Anticuerpos contra receptor de acetilcolina — miastenia gravis'],
  ],
  Gastroenterología: [
    ['TLI'],
    ['PLI'],
    ['Cobalamina'],
    ['Folato'],
    ['Panel gastrointestinal'],
    ['Alfa-1 inhibidor de proteasas'],
    ['Calprotectina fecal'],
    ['Disbiosis fecal'],
    ['Índice de disbiosis'],
    ['PCR gastrointestinal'],
    ['Cultivo fecal', 'tipo_muestra'],
    ['Coproparasitoscópico'],
    ['Sangre oculta en heces'],
    ['Citología gastrointestinal', 'tejido_lateralidad'],
    ['Biopsia gástrica', 'tejido_lateralidad'],
    ['Biopsia intestinal', 'tejido_lateralidad'],
    ['Endoscopia gastrointestinal'],
    ['Gastroscopia'],
    ['Colonoscopia'],
  ],
  'Sistema respiratorio': [
    ['Lavado traqueal'],
    ['Lavado broncoalveolar — BAL'],
    ['Citología de BAL', 'tejido_lateralidad'],
    ['Cultivo bacteriano BAL', 'tipo_muestra'],
    ['Cultivo micológico BAL', 'tipo_muestra'],
    ['PCR respiratoria'],
    ['Panel respiratorio canino', null, 'Perro'],
    ['Panel respiratorio felino', null, 'Gato'],
    ['Broncoscopia'],
    ['Rinoscopia'],
    ['Radiografía torácica'],
    ['TAC torácica'],
    ['Gasometría arterial'],
    ['Pulsioximetría'],
    ['Capnografía'],
  ],
  Reproducción: [
    ['Citología vaginal'],
    ['Progesterona'],
    ['Estradiol'],
    ['LH'],
    ['AMH'],
    ['Relaxina — diagnóstico de gestación'],
    ['Ultrasonido gestacional'],
    ['Radiografía gestacional'],
    ['Cultivo vaginal', 'tipo_muestra'],
    ['Brucella'],
    ['Histopatología uterina/ovárica', 'tejido_lateralidad'],
    ['Espermatograma'],
    ['Conteo espermático'],
    ['Motilidad espermática'],
    ['Morfología espermática'],
    ['Viabilidad espermática'],
    ['Cultivo seminal', 'tipo_muestra'],
    ['Testosterona'],
    ['Citología prostática', 'tejido_lateralidad'],
    ['Ultrasonido prostático'],
    ['Brucella canis'],
  ],
  Oftalmología: [
    ['Prueba de Schirmer'],
    ['Tinción con fluoresceína'],
    ['Tinción con rosa de Bengala'],
    ['Tonometría'],
    ['Oftalmoscopia directa'],
    ['Oftalmoscopia indirecta'],
    ['Biomicroscopía con lámpara de hendidura'],
    ['Gonioscopía'],
    ['Ultrasonido ocular'],
    ['Electrorretinografía — ERG'],
    ['Citología conjuntival', 'tejido_lateralidad'],
    ['Cultivo ocular', 'tipo_muestra'],
    ['PCR ocular'],
    ['Angiografía fluoresceínica'],
    ['Tomografía de coherencia óptica — OCT'],
  ],
  Otología: [
    ['Otoscopia'],
    ['Videootoscopia'],
    ['Citología ótica', 'tejido_lateralidad'],
    ['Cultivo ótico', 'tipo_muestra'],
    ['Antibiograma'],
    ['Miringotomía diagnóstica'],
    ['TAC de oído medio/interno'],
    ['BAER / respuesta auditiva evocada del tronco encefálico'],
  ],
  'Ortopedia y musculoesquelético': [
    ['Radiografía ortopédica', 'zona'],
    ['Evaluación de displasia de cadera'],
    ['PennHIP'],
    ['Evaluación OFA de cadera'],
    ['Evaluación de displasia de codo'],
    ['Artrocentesis'],
    ['Análisis de líquido sinovial'],
    ['Citología de líquido sinovial', 'tejido_lateralidad'],
    ['Cultivo de líquido sinovial', 'tipo_muestra'],
    ['TAC musculoesquelética', 'zona'],
    ['Resonancia musculoesquelética', 'zona'],
    ['Artroscopia'],
    ['Biopsia ósea', 'tejido_lateralidad'],
    ['Cultivo óseo', 'tipo_muestra'],
    ['Densitometría ósea'],
  ],
  'Inmunología y autoinmunes': [
    ['Prueba de Coombs directa'],
    ['Prueba de Coombs indirecta'],
    ['Anticuerpos antinucleares — ANA'],
    ['Factor reumatoide'],
    ['Inmunoglobulinas IgG'],
    ['IgM'],
    ['IgA'],
    ['Electroforesis de proteínas'],
    ['Inmunofijación'],
    ['Inmunofenotipificación'],
    ['Complemento'],
    ['Inmunofluorescencia'],
    ['Anticuerpos contra receptor de acetilcolina'],
    ['Panel de anemia hemolítica inmunomediada'],
    ['Panel inmunológico'],
  ],
  Toxicología: [
    ['Panel toxicológico'],
    ['Etilenglicol'],
    ['Metanol'],
    ['Anticongelante'],
    ['Rodenticidas anticoagulantes'],
    ['Brometalina'],
    ['Colecalciferol'],
    ['Metaldehído'],
    ['Organofosforados'],
    ['Carbamatos'],
    ['Colinesterasa'],
    ['Piretroides'],
    ['Plomo'],
    ['Mercurio'],
    ['Arsénico'],
    ['Cadmio'],
    ['Zinc — análisis toxicológico'],
    ['Cobre — análisis toxicológico'],
    ['Hierro — análisis toxicológico'],
    ['Micotoxinas'],
    ['Aflatoxinas'],
    ['Intoxicación por medicamentos'],
    ['Acetaminofén / paracetamol'],
    ['Salicilatos'],
    ['Cafeína'],
    ['Teobromina / chocolate'],
    ['Xilitol'],
    ['Vitamina D'],
    ['Cannabis / THC'],
    ['Drogas de abuso'],
    ['Análisis toxicológico de contenido gástrico'],
    ['Análisis toxicológico de hígado'],
    ['Análisis toxicológico de sangre'],
    ['Análisis toxicológico de orina'],
  ],
  'Banco de sangre / Medicina transfusional': [
    ['Tipificación DEA 1'],
    ['Tipificación DEA 3'],
    ['Tipificación DEA 4'],
    ['Tipificación DEA 5'],
    ['Tipificación DEA 7'],
    ['Prueba cruzada mayor'],
    ['Prueba cruzada menor'],
    ['Panel de donador sanguíneo canino', null, 'Perro'],
    ['Grupo sanguíneo felino A', null, 'Gato'],
    ['Grupo sanguíneo felino B', null, 'Gato'],
    ['Grupo sanguíneo felino AB', null, 'Gato'],
    ['Antígeno Mik'],
    ['Panel de donador sanguíneo felino', null, 'Gato'],
    ['Prueba cruzada mayor (perro)'],
    ['Prueba cruzada menor (perro)'],
    ['Prueba cruzada mayor (gato)'],
    ['Prueba cruzada menor (gato)'],
  ],
  Genética: [
    ['MDR1 / ABCB1'],
    ['Degeneración progresiva de retina / PRA'],
    ['PRA-prcd'],
    ['Enfermedad de von Willebrand genética'],
    ['Mielopatía degenerativa / SOD1'],
    ['Colapso inducido por ejercicio / EIC'],
    ['Neuropatías hereditarias'],
    ['Miopatías hereditarias'],
    ['Cistinuria'],
    ['Hiperuricosuria'],
    ['Narcolepsia'],
    ['Cardiomiopatía dilatada hereditaria'],
    ['Miocardiopatía arritmogénica'],
    ['Enfermedades de almacenamiento lisosomal'],
    ['Identificación genética / perfil DNA'],
    ['Parentesco'],
    ['PKD / enfermedad renal poliquística'],
    ['HCM / MYBPC3'],
    ['Deficiencia de piruvato quinasa / PKDef'],
    ['Atrofia retinal progresiva felina', null, 'Gato'],
    ['Gangliosidosis'],
    ['Mucopolisacaridosis'],
    ['Grupo sanguíneo genético felino', null, 'Gato'],
    ['Enfermedades hereditarias específicas de raza'],
    ['Sensibilidad a medicamentos MDR1'],
    ['Enfermedades de almacenamiento lisosomal (perro)'],
    ['Enfermedades hereditarias específicas de raza (perro)'],
    ['Identificación genética / perfil DNA (perro)'],
    ['Parentesco (perro)'],
    ['PRA felina', null, 'Gato'],
    ['Enfermedades de almacenamiento lisosomal (gato)'],
    ['Enfermedades hereditarias específicas de raza (gato)'],
    ['Perfil genético / DNA (gato)'],
    ['Parentesco (gato)'],
  ],
  'Análisis de líquidos corporales': [
    ['Análisis de líquido pleural', 'componentes_liquido'],
    ['Análisis de líquido peritoneal', 'componentes_liquido'],
    ['Análisis de líquido pericárdico', 'componentes_liquido'],
    ['Análisis de líquido sinovial', 'componentes_liquido'],
    ['Análisis de líquido cefalorraquídeo', 'componentes_liquido'],
    ['Análisis de líquido prostático', 'componentes_liquido'],
    ['Análisis de líquido de quistes', 'componentes_liquido'],
    ['Análisis de derrames cavitarios', 'componentes_liquido'],
    ['Líquido pleural', 'componentes_liquido'],
    ['Líquido peritoneal', 'componentes_liquido'],
    ['Líquido pericárdico', 'componentes_liquido'],
    ['Líquido sinovial', 'componentes_liquido'],
    ['Líquido cefalorraquídeo', 'componentes_liquido'],
    ['Líquido prostático', 'componentes_liquido'],
    ['Líquido de quistes', 'componentes_liquido'],
    ['Derrames cavitarios', 'componentes_liquido'],
  ],
  'Monitorización de fármacos': [
    ['Fenobarbital'],
    ['Bromuro'],
    ['Levetiracetam'],
    ['Digoxina'],
    ['Ciclosporina'],
    ['Tacrolimus'],
    ['Micofenolato'],
    ['Teofilina'],
    ['Gentamicina'],
    ['Amikacina'],
    ['Vancomicina'],
    ['Curva de glucosa'],
    ['Monitor continuo de glucosa'],
    ['Insulina / curvas de glucosa'],
  ],
  Odontología: [
    ['Evaluación odontológica'],
    ['Radiografía dental intraoral'],
    ['Serie radiográfica dental completa'],
    ['Sondaje periodontal'],
    ['Índice periodontal'],
    ['Citología oral', 'tejido_lateralidad'],
    ['Biopsia oral', 'tejido_lateralidad'],
    ['Histopatología oral', 'tejido_lateralidad'],
    ['Cultivo bacteriano oral', 'tipo_muestra'],
    ['TAC maxilofacial'],
  ],
  'Perfiles clínicos / Paneles': [
    ['Función renal', null, 'Perro'],
    ['Perfil metabólico', null, 'Perro'],
    ['Perfil respiratorio felino', null, 'Gato'],
    ['Perfil preoperatorio básico'],
    ['Perfil preoperatorio completo'],
    ['Perfil básico'],
    ['Perfil general'],
    ['Perfil integral'],
    ['Perfil geriátrico'],
    ['Perfil pediátrico'],
    ['Perfil renal'],
    ['Perfil hepático'],
    ['Perfil gastrointestinal'],
    ['Perfil pancreático'],
    ['Perfil tiroideo'],
    ['Perfil adrenal'],
    ['Perfil endocrino'],
    ['Perfil cardiaco'],
    ['Perfil neurológico'],
    ['Perfil reproductivo'],
    ['Perfil de coagulación'],
    ['Perfil de anemia'],
    ['Perfil de anemia hemolítica'],
    ['Perfil de fiebre'],
    ['Perfil de pérdida de peso'],
    ['Perfil de poliuria/polidipsia'],
    ['Perfil dermatológico'],
    ['Perfil de alergias'],
    ['Perfil toxicológico'],
    ['Perfil infeccioso'],
    ['Perfil de enfermedades vectoriales'],
    ['Perfil de donador sanguíneo'],
    ['Panel respiratorio canino', null, 'Perro'],
    ['Panel respiratorio felino', null, 'Gato'],
    ['Panel gastrointestinal canino', null, 'Perro'],
    ['Panel gastrointestinal felino', null, 'Gato'],
    ['Panel neurológico canino', null, 'Perro'],
    ['Panel neurológico felino', null, 'Gato'],
  ],
  'Procedimientos diagnósticos': [
    ['Endoscopia'],
    ['Gastroscopia'],
    ['Colonoscopia'],
    ['Rinoscopia'],
    ['Broncoscopia'],
    ['Cistoscopia'],
    ['Otoscopia'],
    ['Videootoscopia'],
    ['Laparoscopia diagnóstica'],
    ['Artroscopia'],
    ['Biopsia guiada por ultrasonido', 'tejido_lateralidad'],
    ['Punción aspirativa guiada por ultrasonido', 'tejido_lateralidad'],
    ['Punción de médula ósea'],
    ['Biopsia de médula ósea', 'tejido_lateralidad'],
    ['Toracocentesis diagnóstica'],
    ['Abdominocentesis diagnóstica'],
    ['Pericardiocentesis diagnóstica'],
    ['Artrocentesis'],
    ['Punción de líquido cefalorraquídeo'],
  ],
};

const estudiosNoCanonicos = new Set([
  'Hematología::Fibrinógeno',
  'Uroanálisis::Cortisol/creatinina urinaria',
  'Uroanálisis::Cultivo de orina',
  'Uroanálisis::Antibiograma urinario',
  'Enfermedades infecciosas - Gato::Cryptosporidium PCR',
  'Enfermedades infecciosas - Gato::Giardia PCR',
  'Enfermedades infecciosas - Perro::Panel de donador sanguíneo canino',
  'Enfermedades infecciosas - Gato::Panel de donador sanguíneo felino',
  'Dermatología::Citología cutánea',
  'Dermatología::Citología ótica',
  'Dermatología::Cultivo micológico',
  'Dermatología::Cultivo bacteriano de piel',
  'Oncología y diagnóstico molecular::Biopsia de médula ósea',
  'Neurología::Análisis de líquido cefalorraquídeo',
  'Neurología::Anticuerpos contra receptor de acetilcolina',
  'Neurología::Mielografía',
  'Neurología::Cultivo de LCR',
  'Gastroenterología::Colonoscopia',
  'Gastroenterología::Cultivo fecal',
  'Gastroenterología::Gastroscopia',
  'Sistema respiratorio::Broncoscopia',
  'Sistema respiratorio::Gasometría arterial',
  'Sistema respiratorio::Panel respiratorio canino',
  'Sistema respiratorio::Panel respiratorio felino',
  'Sistema respiratorio::Rinoscopia',
  'Sistema respiratorio::Cultivo bacteriano BAL',
  'Reproducción::Citología vaginal',
  'Reproducción::Estradiol',
  'Reproducción::LH',
  'Reproducción::Progesterona',
  'Reproducción::Testosterona',
  'Reproducción::Ultrasonido gestacional',
  'Oftalmología::Citología conjuntival',
  'Oftalmología::Cultivo ocular',
  'Otología::Antibiograma',
  'Otología::Cultivo ótico',
  'Otología::Citología ótica',
  'Otología::Otoscopia',
  'Otología::Videootoscopia',
  'Ortopedia y musculoesquelético::Análisis de líquido sinovial',
  'Ortopedia y musculoesquelético::Artrocentesis',
  'Ortopedia y musculoesquelético::Artroscopia',
  'Ortopedia y musculoesquelético::Citología de líquido sinovial',
  'Ortopedia y musculoesquelético::Cultivo de líquido sinovial',
  'Bacteriología::Antibiograma',
  'Bacteriología::Cultivo de sangre / hemocultivo',
  'Bacteriología::Cultivo de orina / urocultivo',
]);

function campoAdicionalCanonico(nombre, campoAdicional) {
  if (campoAdicional !== 'tipo_muestra') return campoAdicional ?? null;
  if (['Cultivo bacteriano aerobio', 'Cultivo bacteriano anaerobio'].includes(nombre)) {
    return campoAdicional;
  }
  if (/^(cultivo|urocultivo|hemocultivo)/i.test(nombre)) return null;
  return campoAdicional;
}

function permiteAntibiograma(nombre) {
  return /^(cultivo|urocultivo|hemocultivo)/i.test(nombre) && !/(micológico|hongos)/i.test(nombre);
}

exports.seed = async function seed(knex) {
  await knex('catalogo_estudios').del();

  const categorias = await knex('catalogo_categorias_estudio').select('id', 'nombre');
  const categoriaIdPorNombre = Object.fromEntries(categorias.map((c) => [c.nombre, c.id]));
  const generarCodigo = crearGeneradorCodigo();

  const rows = Object.entries(estudiosPorCategoria).flatMap(([categoriaNombre, estudios]) => {
    const categoriaId = categoriaIdPorNombre[categoriaNombre];
    if (!categoriaId) {
      throw new Error(
        `Categoría "${categoriaNombre}" no existe en catalogo_categorias_estudio — revisa 03_catalogo_categorias_estudio.js`,
      );
    }
    return estudios
      .filter(([nombre]) => !estudiosNoCanonicos.has(`${categoriaNombre}::${nombre}`))
      .map(([nombre, campoAdicional, especie]) => {
        const campoCanonico = campoAdicionalCanonico(nombre, campoAdicional);
        return {
          categoria_id: categoriaId,
          codigo: generarCodigo(nombre),
          nombre,
          campo_adicional: campoCanonico,
          especie: especie ?? null,
          permite_antibiograma: permiteAntibiograma(nombre),
        };
      });
  });

  await knex('catalogo_estudios').insert(rows);
};
